server:
  port: 8030
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      default-Zone: https://localhost:8761/eureka/
zuul:
  routes:
    provider: /p/** #给服务提供者provider 设置映射