server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          url: https://github.com/UzumakiNagato/aispringcloud2.git
          searchPaths: config
          username: UzumakiNagato
          password: Uzumaki12499921
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
